#### ChA-MAEViT results on Table 1 in the paper

1. So2Sat (1 GPU)
python main.py ++model.training_sample=DCP ++model.init_values=1 ++model.patch_size=8 ++train.max_grad_norm=1 ++model.attention_cls=v2 ++train.num_workers=3 ++train.learning_rate=0.0004 ++logging.run_name=STest-r2-CodeChAMAEViT ++train.batch_size=128 ++eval.eval_batch_size=512 ++data.so2sat.normalization.use_mean_std=True ++model.mae_lambda=0.99 ++model.mae_loss_norm=norm_pix_loss ++model.model_size=small ++eval.eval_every_epochs=5 ++model.decoder.dcp_p_patch=0 ++model.decoder.dcp_p_channel=0 ++model.num_memory_tokens=8 ++model.use_self_image_norm=False ++eval.eval_before_training=False ++train.checkpointing_limit=1 ++model.encoder_pooling=cls_attn_pooling ++data.training_dataset=so2sat ++model.cross_entropy_lambda=0.01 ++model.cross_entropy_temperature=10 ++model.dcp_at_least_mask_one_channel=True ++model.depth=11 ++model.decoder.depth=1 ++train.seed=74733

2. CHAMMI (1 GPU, reported `score/allen_hpa`)
python main.py ++model.training_sample=DCP ++model.init_values=1 ++model.patch_size=16 ++train.max_grad_norm=1 ++model.attention_cls=v2 ++train.num_workers=3 ++train.learning_rate=0.0004 ++logging.run_name=CTest-r2-R2CodeChAMAEViT ++train.batch_size=80 ++eval.eval_batch_size=256 ++data.chammiv1.normalization.use_mean_std=True ++model.mae_lambda=0.99 ++model.mae_loss_norm=norm_pix_loss ++model.model_size=small ++eval.eval_every_epochs=5 ++model.decoder.dcp_p_patch=0.5 ++model.decoder.dcp_p_channel=0.5 ++model.decoder.dcp_mask_ratio=0.75 ++model.num_memory_tokens=4 ++model.proxy_loss_lambda=0.01 ++eval.eval_before_training=False ++train.checkpointing_limit=1 ++model.use_proxy_head=True ++model.encoder_pooling=cls_attn_pooling_sigmoid ++model.diverse_patch_token_weight=0.001 ++model.diverse_channel_token_weight=0.0001 ++data.training_dataset=chammiv1 ++model.diverse_patch_token_gamma_s=0.5 ++model.diverse_patch_token_gamma_d=1 ++model.cross_entropy_temperature=10 ++model.depth=11 ++model.decoder.depth=1 ++train.seed=36860

3. JUMPCP (2 GPUs)
accelerate launch --main_process_port=9999 --num_processes=2 main.py ++model.training_sample=DCP ++model.init_values=1 ++model.patch_size=16 ++train.max_grad_norm=1 ++model.attention_cls=v2 ++train.num_workers=3 ++train.learning_rate=0.0004 ++logging.run_name=JTestCodeChAMAEViT ++train.batch_size=32 ++eval.eval_batch_size=300 ++data.chammiv1.normalization.use_mean_std=True ++model.mae_lambda=0.99 ++model.mae_loss_norm=norm_pix_loss ++model.model_size=small ++eval.eval_every_epochs=5 ++model.decoder.dcp_p_patch=0.5 ++model.decoder.dcp_p_channel=0.5 ++model.num_memory_tokens=4 ++model.proxy_loss_lambda=0 ++model.use_self_image_norm=False ++eval.eval_before_training=False ++train.checkpointing_limit=1 ++model.use_proxy_head=False ++model.encoder_pooling=cls_attn_pooling_sigmoid ++model.diverse_patch_token_weight=0.000001 ++model.diverse_channel_token_weight=0.001 ++model.diverse_patch_token_gamma_s=1 ++model.diverse_patch_token_gamma_d=4 ++data.training_dataset=jumpcp ++train.weight_decay=0.04 ++model.depth=11 ++model.cross_entropy_lambda=0.01 ++train.lr_warmup_epochs=10 ++train.seed=33677 

