attention_cls: v2 ## choices: {regular, v1, v2} (default v2).  v1 and v2 is more memory efficient. 
model_size: small 
patch_size: 16
depth: 12
training_sample: ~ # choices: {hcs, ~}
init_values: ~ # choices {~, a float number (e.g., 1.0)}. Used for LayerScale in DINOv2. Set to ~ to disable this layer. Refer to https://github.com/facebookresearch/dinov2/blob/main/dinov2/layers/layer_scale.py
encoder_pooling: cls_token  # choices: {cls_token, cls_attn_pooling_sigmoid, cls_attn_pooling}
use_channel_tokens: True
channel_tokens_init: orthogonal # choices: {random, orthogonal, zero}
use_self_image_norm: False ## if True, apply self-normalization (InstanceNorm2d without learnable parameters) to each channel independently before feeding into the model. 
num_memory_tokens: 4 ## number of ChA-MAEViT memory tokens

########## LOSSES ##########
## proxy loss
proxy_loss_lambda: 0 ## used in CHAMMI for representation learning tasks. Set to 0.01 to use the proxy loss
proxy_temperature: 0.11
proxy_orthogonal_init: True
num_proxies: FILL_LATER ## usually set to the number of classes in the dataset
use_proxy_head: False ## if True, use a linear layer to project the CLS token before computing the proxy loss

## cross-entropy loss
cross_entropy_lambda: 0.0 ## used in JUMPCP, So2Sat for classification tasks. Set to 0.01 to use the cross-entropy loss
cross_entropy_temperature: 5.0

## diverse regularization
diverse_patch_token_weight: 0.00001
diverse_patch_token_gamma_s: 1.0
diverse_patch_token_gamma_d: 4.0
diverse_channel_token_weight: 0.0001

## MAE loss
mae_lambda: 0.99 ## set to 0 to disable the MAE loss
mae_recon_fourier_lambda: 0.01
mae_loss_norm: norm_pix_loss

################### channel-aware decoder ###################
decoder:
  decoder_type: chamaevit_decoder 
  depth: 1  
  embed_dim: ~
  mlp_ratio: 4
  norm_layer: 
    _partial_: true
    _target_: torch.nn.LayerNorm
    eps: 1e-06
  num_heads: 16
  qkv_bias: false 
  mask_recon_fourier_loss: True
  dcp_at_least_mask_one_channel: False
  #### Two simple configs for a good starting point:
  ## DCP Combination Masking: Combines both channel and patch masks into a single mask. Set `dcp_p_patch` = `dcp_p_channel` = 0 for this option. As for `dcp_mask_ratio`,  as we already mask out some channels, using a small patch mask ratio like 0.25 works well
  ## DCP Alternate Masking: Alternates between channel mask and patch mask. To use this, set `dcp_p_patch` = `dcp_p_channel` = 0.5. For  `dcp_mask_ratio`, it can be set to a higher value (e.g, try 0.25 or 0.75)
  dcp_p_patch: 0.5  ## a float number, range [0, 1]
  dcp_p_channel: 0.5  ## a float number, range [0, 1].   note `dcp_p_patch` + `dcp_p_channel` <= 1.
  dcp_mask_ratio: 0.75  ##  a float number, range (0, 1).  For DCP Combination Masking, set to 0.25; For DCP Alternate Masking, we can try 0.25, or a higher value like 0.75
